package com.example.kitsu.presentation.models.mangamodels

import com.example.kitsu.domain.models.mangamodels.Attributes

data class AttributesUi(
    val abbreviatedTitles: List<String>?,
    val ageRating: String?,
    val ageRatingGuide: String?,
    val averageRating: String?,
    val canonicalTitle: String?,
    val chapterCount: Int?,
    val coverImageTopOffset: Int?,
    val createdAt: String?,
    val description: String?,
    val endDate: String?,
    val favoritesCount: Int?,
    val mangaType: String?,
    val popularityRank: Int?,
    val posterImage: PosterImageUi?,
    val ratingFrequencies: RatingFrequenciesUi?,
    val ratingRank: Int?,
    val serialization: String?,
    val slug: String?,
    val startDate: String?,
    val status: String?,
    val subtype: String?,
    val synopsis: String?,
    val tba: String?,
    val titles: TitlesUi?,
    val updatedAt: String?,
    val userCount: Int?,
    val volumeCount: Int?
)

fun Attributes.toUi() = AttributesUi(
    abbreviatedTitles,
    ageRating,
    ageRatingGuide,
    averageRating,
    canonicalTitle,
    chapterCount,
    coverImageTopOffset,
    createdAt,
    description,
    endDate,
    favoritesCount,
    mangaType,
    popularityRank,
    posterImage?.toUi(),
    ratingFrequencies?.toUi(),
    ratingRank,
    serialization,
    slug,
    startDate,
    status,
    subtype,
    synopsis,
    tba,
    titles?.toUi(),
    updatedAt,
    userCount,
    volumeCount,
)